# Git & version control
brew "git"
brew "gh"
brew "lazygit"
brew "git-delta"

# Editors, multiplexers & monitors
brew "neovim"
brew "lua-language-server"
brew "stylua"
brew "tmux"
brew "sesh"
brew "zellij"
brew "btop"
brew "fastfetch"

# CLI utilities
brew "ripgrep"
brew "fd"
brew "bat"
brew "eza"
brew "fzf"
brew "jq"
brew "yq"
brew "buku"
brew "newsboat"
brew "ffmpeg"
brew "xorriso"
brew "terminal-notifier"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"

# Dev & cloud tooling
brew "node@22"
brew "pnpm"
brew "ollama"
brew "awscli"
brew "saml2aws"
brew "kubectx"
brew "k3d"
tap "minio/stable"
brew "minio/stable/mc"

cask "ghostty"
cask "1password"
cask "badgeify"
cask "claude"
cask "conductor"
cask "cursor"
cask "dbngin"
cask "docker-desktop"
cask "firefox"
cask "google-chrome"
cask "matterhorn"
cask "mattermost"
# Moom: install Moom 3 (classic) manually from manytricks.com — the `moom` cask is Moom 4.x
cask "microsoft-powerpoint"
cask "microsoft-teams"
cask "obsidian"
cask "tableplus"
cask "tailscale-app"
cask "wispr-flow"

cask "font-blex-mono-nerd-font"
cask "font-geist-mono-nerd-font"
cask "font-meslo-lg-nerd-font"
cask "font-sf-mono-nerd-font-ligaturized"
cask "font-symbols-only-nerd-font"
