tap "FelixKratz/formulae"
tap "nikitabobko/tap"

brew "git"
brew "neovim"
brew "tmux"
brew "starship"
brew "btop"
brew "ripgrep"
brew "bat"
brew "eza"
brew "fzf"
brew "gh"
brew "lazygit"
brew "git-delta"
brew "jq"
brew "yq"
brew "fd"
brew "zoxide"
brew "mise"
brew "yazi"
brew "ffmpegthumbnailer"
brew "poppler"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "sketchybar"

cask "ghostty"
cask "1password"
cask "obsidian"
cask "raycast"
cask "nikitabobko/tap/aerospace"
cask "hiddenbar"
cask "tailscale"

cask "font-geist-mono-nerd-font"
cask "font-symbols-only-nerd-font"
