vim.o.background = "light"
vim.g.colors_name = "conductor-light"

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Palette
local bg = "#ffffff"
local bg1 = "#fafaf9"
local bg2 = "#f5f3f1"
local bg3 = "#eae8e6"
local bg4 = "#ddd9d6"
local fg = "#2c2826"
local fg1 = "#413a35"
local muted = "#8e8885"
local comment = "#8e8885"
local dim = "#b0aaa5"
local red = "#b83a3a"
local red_bright = "#d94444"
local green = "#3a7a40"
local yellow = "#9a7030"
local yellow_bright = "#b8883a"
local blue = "#2a6ab5"
local blue_bright = "#3d7ed4"
local magenta = "#8a4f78"
local cyan = "#3a7a6e"
local cyan_bright = "#4a9488"
local search_bg = "#f0e0c0"
local search_cur = "#e0cc9a"
local diff_add = "#e8f5e8"
local diff_change = "#f5f0e0"
local diff_delete = "#f8e8e8"

-- Base UI
hi("Normal", { fg = fg, bg = bg })
hi("NormalFloat", { fg = fg, bg = bg1 })
hi("NormalNC", { fg = fg, bg = bg })
hi("FloatBorder", { fg = bg4, bg = bg1 })
hi("FloatTitle", { fg = yellow, bg = bg1, bold = true })
hi("Cursor", { fg = bg, bg = yellow })
hi("lCursor", { fg = bg, bg = yellow })
hi("CursorLine", { bg = bg1 })
hi("CursorColumn", { bg = bg1 })
hi("ColorColumn", { bg = bg1 })
hi("LineNr", { fg = dim })
hi("CursorLineNr", { fg = yellow, bold = true })
hi("SignColumn", { fg = dim, bg = bg })
hi("FoldColumn", { fg = dim, bg = bg })
hi("Folded", { fg = comment, bg = bg2 })
hi("VertSplit", { fg = bg4 })
hi("WinSeparator", { fg = bg4 })
hi("StatusLine", { fg = fg, bg = bg2 })
hi("StatusLineNC", { fg = comment, bg = bg1 })
hi("TabLine", { fg = comment, bg = bg1 })
hi("TabLineFill", { bg = bg1 })
hi("TabLineSel", { fg = fg, bg = bg, bold = true })
hi("WinBar", { fg = fg, bg = bg })
hi("WinBarNC", { fg = comment, bg = bg })
hi("Title", { fg = yellow, bold = true })
hi("NonText", { fg = bg4 })
hi("SpecialKey", { fg = bg4 })
hi("Whitespace", { fg = bg3 })
hi("EndOfBuffer", { fg = bg })
hi("Conceal", { fg = comment })
hi("MatchParen", { fg = yellow, bold = true, underline = true })
hi("Visual", { bg = bg3 })
hi("VisualNOS", { bg = bg3 })
hi("Search", { fg = fg, bg = search_bg })
hi("IncSearch", { fg = bg, bg = yellow })
hi("CurSearch", { fg = bg, bg = yellow_bright })
hi("Substitute", { fg = bg, bg = red })
hi("Pmenu", { fg = fg, bg = bg2 })
hi("PmenuSel", { fg = bg, bg = yellow })
hi("PmenuSbar", { bg = bg3 })
hi("PmenuThumb", { bg = muted })
hi("WildMenu", { fg = bg, bg = yellow })
hi("Question", { fg = green })
hi("QuickFixLine", { bg = bg2 })
hi("MoreMsg", { fg = green })
hi("ModeMsg", { fg = fg, bold = true })
hi("ErrorMsg", { fg = red_bright })
hi("WarningMsg", { fg = yellow_bright })
hi("Directory", { fg = blue })
hi("SpellBad", { sp = red, undercurl = true })
hi("SpellCap", { sp = yellow, undercurl = true })
hi("SpellLocal", { sp = cyan, undercurl = true })
hi("SpellRare", { sp = magenta, undercurl = true })

-- Syntax
hi("Comment", { fg = comment, italic = true })
hi("Constant", { fg = yellow_bright })
hi("String", { fg = green })
hi("Character", { fg = green })
hi("Number", { fg = yellow_bright })
hi("Boolean", { fg = yellow_bright })
hi("Float", { fg = yellow_bright })
hi("Identifier", { fg = fg })
hi("Function", { fg = blue })
hi("Statement", { fg = magenta })
hi("Conditional", { fg = magenta })
hi("Repeat", { fg = magenta })
hi("Label", { fg = magenta })
hi("Operator", { fg = muted })
hi("Keyword", { fg = magenta })
hi("Exception", { fg = magenta })
hi("PreProc", { fg = cyan })
hi("Include", { fg = magenta })
hi("Define", { fg = magenta })
hi("Macro", { fg = magenta })
hi("PreCondit", { fg = cyan })
hi("Type", { fg = yellow })
hi("StorageClass", { fg = yellow })
hi("Structure", { fg = yellow })
hi("Typedef", { fg = yellow })
hi("Special", { fg = cyan })
hi("SpecialChar", { fg = cyan })
hi("Tag", { fg = red })
hi("Delimiter", { fg = muted })
hi("SpecialComment", { fg = comment, bold = true })
hi("Debug", { fg = red })
hi("Underlined", { underline = true })
hi("Ignore", { fg = dim })
hi("Error", { fg = red_bright })
hi("Todo", { fg = yellow, bg = bg2, bold = true })

-- Treesitter
hi("@variable", { fg = fg })
hi("@variable.builtin", { fg = red, italic = true })
hi("@variable.parameter", { fg = fg1 })
hi("@variable.member", { fg = cyan })
hi("@constant", { fg = yellow_bright })
hi("@constant.builtin", { fg = yellow_bright, italic = true })
hi("@constant.macro", { fg = yellow_bright })
hi("@module", { fg = yellow })
hi("@string", { fg = green })
hi("@string.escape", { fg = cyan })
hi("@string.regexp", { fg = cyan })
hi("@string.special", { fg = cyan })
hi("@character", { fg = green })
hi("@number", { fg = yellow_bright })
hi("@boolean", { fg = yellow_bright })
hi("@float", { fg = yellow_bright })
hi("@function", { fg = blue })
hi("@function.builtin", { fg = blue, italic = true })
hi("@function.call", { fg = blue })
hi("@function.macro", { fg = magenta })
hi("@method", { fg = blue })
hi("@method.call", { fg = blue })
hi("@constructor", { fg = yellow })
hi("@keyword", { fg = magenta })
hi("@keyword.function", { fg = magenta })
hi("@keyword.operator", { fg = magenta })
hi("@keyword.return", { fg = magenta })
hi("@keyword.import", { fg = magenta })
hi("@keyword.conditional", { fg = magenta })
hi("@keyword.repeat", { fg = magenta })
hi("@keyword.exception", { fg = magenta })
hi("@operator", { fg = muted })
hi("@punctuation.delimiter", { fg = muted })
hi("@punctuation.bracket", { fg = fg1 })
hi("@punctuation.special", { fg = cyan })
hi("@type", { fg = yellow })
hi("@type.builtin", { fg = yellow, italic = true })
hi("@type.definition", { fg = yellow })
hi("@type.qualifier", { fg = magenta })
hi("@property", { fg = cyan })
hi("@attribute", { fg = yellow })
hi("@tag", { fg = red })
hi("@tag.attribute", { fg = yellow })
hi("@tag.delimiter", { fg = muted })
hi("@markup.heading", { fg = yellow, bold = true })
hi("@markup.strong", { bold = true })
hi("@markup.italic", { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.link", { fg = blue, underline = true })
hi("@markup.link.url", { fg = cyan, underline = true })
hi("@markup.raw", { fg = green })
hi("@markup.list", { fg = muted })
hi("@comment", { fg = comment, italic = true })

-- LSP Semantic Tokens
hi("@lsp.type.class", { fg = yellow })
hi("@lsp.type.decorator", { fg = magenta })
hi("@lsp.type.enum", { fg = yellow })
hi("@lsp.type.enumMember", { fg = yellow_bright })
hi("@lsp.type.function", { fg = blue })
hi("@lsp.type.interface", { fg = yellow })
hi("@lsp.type.macro", { fg = magenta })
hi("@lsp.type.method", { fg = blue })
hi("@lsp.type.namespace", { fg = yellow })
hi("@lsp.type.parameter", { fg = fg1 })
hi("@lsp.type.property", { fg = cyan })
hi("@lsp.type.struct", { fg = yellow })
hi("@lsp.type.type", { fg = yellow })
hi("@lsp.type.typeParameter", { fg = yellow })
hi("@lsp.type.variable", { fg = fg })

-- Diagnostics
hi("DiagnosticError", { fg = red_bright })
hi("DiagnosticWarn", { fg = yellow_bright })
hi("DiagnosticInfo", { fg = blue_bright })
hi("DiagnosticHint", { fg = cyan_bright })
hi("DiagnosticOk", { fg = green })
hi("DiagnosticUnderlineError", { sp = red_bright, undercurl = true })
hi("DiagnosticUnderlineWarn", { sp = yellow_bright, undercurl = true })
hi("DiagnosticUnderlineInfo", { sp = blue_bright, undercurl = true })
hi("DiagnosticUnderlineHint", { sp = cyan_bright, undercurl = true })
hi("DiagnosticVirtualTextError", { fg = red_bright, bg = diff_delete })
hi("DiagnosticVirtualTextWarn", { fg = yellow_bright, bg = diff_change })
hi("DiagnosticVirtualTextInfo", { fg = blue_bright, bg = bg2 })
hi("DiagnosticVirtualTextHint", { fg = cyan_bright, bg = bg2 })

-- Git signs
hi("GitSignsAdd", { fg = green })
hi("GitSignsChange", { fg = yellow })
hi("GitSignsDelete", { fg = red })
hi("GitSignsAddNr", { fg = green })
hi("GitSignsChangeNr", { fg = yellow })
hi("GitSignsDeleteNr", { fg = red })
hi("GitSignsAddLn", { bg = diff_add })
hi("GitSignsChangeLn", { bg = diff_change })
hi("GitSignsDeleteLn", { bg = diff_delete })

-- Diff
hi("DiffAdd", { bg = diff_add })
hi("DiffChange", { bg = diff_change })
hi("DiffDelete", { bg = diff_delete })
hi("DiffText", { bg = search_cur })
hi("diffAdded", { fg = green })
hi("diffRemoved", { fg = red })
hi("diffChanged", { fg = yellow })

-- Telescope
hi("TelescopeNormal", { fg = fg, bg = bg1 })
hi("TelescopeBorder", { fg = bg4, bg = bg1 })
hi("TelescopeTitle", { fg = yellow, bold = true })
hi("TelescopePromptNormal", { fg = fg, bg = bg2 })
hi("TelescopePromptBorder", { fg = bg4, bg = bg2 })
hi("TelescopePromptTitle", { fg = bg, bg = yellow, bold = true })
hi("TelescopePromptPrefix", { fg = yellow })
hi("TelescopeSelection", { bg = bg3 })
hi("TelescopeSelectionCaret", { fg = yellow })
hi("TelescopeMatching", { fg = yellow, bold = true })
hi("TelescopeResultsTitle", { fg = yellow })
hi("TelescopePreviewTitle", { fg = yellow })

-- Snacks
hi("SnacksPickerInput", { fg = fg, bg = bg2 })
hi("SnacksPickerInputBorder", { fg = bg4, bg = bg2 })
hi("SnacksPickerInputTitle", { fg = bg, bg = yellow, bold = true })
hi("SnacksPickerList", { fg = fg, bg = bg1 })
hi("SnacksPickerListBorder", { fg = bg4, bg = bg1 })
hi("SnacksPickerPreview", { fg = fg, bg = bg1 })
hi("SnacksPickerPreviewBorder", { fg = bg4, bg = bg1 })
hi("SnacksPickerPreviewTitle", { fg = yellow, bold = true })
hi("SnacksPickerListCursorLine", { bg = bg3 })
hi("SnacksPickerMatch", { fg = yellow, bold = true })
hi("SnacksDashboardHeader", { fg = yellow })
hi("SnacksDashboardIcon", { fg = blue })
hi("SnacksDashboardKey", { fg = magenta })
hi("SnacksDashboardDesc", { fg = fg1 })
hi("SnacksDashboardFooter", { fg = comment })
hi("SnacksNotifierInfo", { fg = blue_bright })
hi("SnacksNotifierWarn", { fg = yellow_bright })
hi("SnacksNotifierError", { fg = red_bright })
hi("SnacksIndent", { fg = bg3 })
hi("SnacksIndentScope", { fg = bg4 })

-- NeoTree
hi("NeoTreeNormal", { fg = fg, bg = bg1 })
hi("NeoTreeNormalNC", { fg = fg, bg = bg1 })
hi("NeoTreeDirectoryName", { fg = blue })
hi("NeoTreeDirectoryIcon", { fg = blue })
hi("NeoTreeRootName", { fg = yellow, bold = true })
hi("NeoTreeFileName", { fg = fg })
hi("NeoTreeFileIcon", { fg = fg })
hi("NeoTreeGitAdded", { fg = green })
hi("NeoTreeGitModified", { fg = yellow })
hi("NeoTreeGitDeleted", { fg = red })
hi("NeoTreeGitConflict", { fg = red_bright, bold = true })
hi("NeoTreeGitUntracked", { fg = muted })
hi("NeoTreeIndentMarker", { fg = bg4 })
hi("NeoTreeWinSeparator", { fg = bg4, bg = bg })
hi("NeoTreeCursorLine", { bg = bg2 })

-- Flash
hi("FlashLabel", { fg = bg, bg = yellow, bold = true })
hi("FlashMatch", { fg = fg, bg = search_bg })
hi("FlashCurrent", { fg = bg, bg = yellow_bright })
hi("FlashBackdrop", { fg = comment })

-- Lazy
hi("LazyButton", { fg = fg, bg = bg3 })
hi("LazyButtonActive", { fg = bg, bg = yellow, bold = true })
hi("LazyH1", { fg = bg, bg = yellow, bold = true })
hi("LazySpecial", { fg = yellow })
hi("LazyProgressDone", { fg = yellow })
hi("LazyProgressTodo", { fg = bg4 })

-- Mini
hi("MiniIndentscopeSymbol", { fg = bg4 })

-- Which-key
hi("WhichKey", { fg = yellow })
hi("WhichKeyGroup", { fg = blue })
hi("WhichKeyDesc", { fg = fg1 })
hi("WhichKeySeparator", { fg = comment })
hi("WhichKeyValue", { fg = muted })

-- Noice / notify
hi("NoiceCmdlinePopup", { fg = fg, bg = bg1 })
hi("NoiceCmdlinePopupBorder", { fg = bg4, bg = bg1 })
hi("NoiceCmdlineIcon", { fg = yellow })
hi("NotifyINFOBorder", { fg = blue })
hi("NotifyINFOTitle", { fg = blue })
hi("NotifyINFOIcon", { fg = blue })
hi("NotifyWARNBorder", { fg = yellow })
hi("NotifyWARNTitle", { fg = yellow })
hi("NotifyWARNIcon", { fg = yellow })
hi("NotifyERRORBorder", { fg = red })
hi("NotifyERRORTitle", { fg = red })
hi("NotifyERRORIcon", { fg = red })
