vim.o.background = "dark"
vim.g.colors_name = "everforest-dark"

local hi = function(group, opts)
  vim.api.nvim_set_hl(0, group, opts)
end

-- Everforest Dark (Hard contrast)
local bg = "#1E2326"
local bg_dark = "#272E33"
local bg_highlight = "#374145"
local bg_float = "#272E33"
local fg = "#D3C6AA"
local fg_dark = "#9DA9A0"
local fg_gutter = "#414B50"
local dark3 = "#7A8478"
local comment = "#7A8478"
local dark5 = "#859289"
local blue = "#7FBBB3"
local cyan = "#83C092"
local blue1 = "#7FBBB3"
local blue2 = "#83C092"
local blue5 = "#9DA9A0"
local blue6 = "#A7C080"
local blue7 = "#374145"
local magenta = "#D699B6"
local magenta2 = "#E67E80"
local orange = "#E69875"
local yellow = "#DBBC7F"
local green = "#A7C080"
local green1 = "#83C092"
local teal = "#83C092"
local red = "#E67E80"
local diff_add = "#425047"
local diff_change = "#45443C"
local diff_delete = "#4C3743"
local search_bg = "#43414A"

hi("Normal", { fg = fg, bg = bg })
hi("NormalFloat", { fg = fg, bg = bg_float })
hi("NormalNC", { fg = fg, bg = bg })
hi("FloatBorder", { fg = blue, bg = bg_float })
hi("FloatTitle", { fg = blue, bg = bg_float, bold = true })
hi("Cursor", { fg = bg, bg = fg })
hi("lCursor", { fg = bg, bg = fg })
hi("CursorLine", { bg = bg_highlight })
hi("CursorColumn", { bg = bg_highlight })
hi("ColorColumn", { bg = bg_highlight })
hi("LineNr", { fg = fg_gutter })
hi("CursorLineNr", { fg = orange, bold = true })
hi("SignColumn", { fg = fg_gutter, bg = bg })
hi("FoldColumn", { fg = comment, bg = bg })
hi("Folded", { fg = blue, bg = fg_gutter })
hi("VertSplit", { fg = bg })
hi("WinSeparator", { fg = bg })
hi("StatusLine", { fg = fg_dark, bg = bg_dark })
hi("StatusLineNC", { fg = fg_gutter, bg = bg_dark })
hi("TabLine", { fg = dark5, bg = bg_dark })
hi("TabLineFill", { bg = bg_dark })
hi("TabLineSel", { fg = bg, bg = blue, bold = true })
hi("WinBar", { fg = fg, bg = bg })
hi("WinBarNC", { fg = comment, bg = bg })
hi("Title", { fg = blue, bold = true })
hi("NonText", { fg = dark3 })
hi("SpecialKey", { fg = dark3 })
hi("Whitespace", { fg = fg_gutter })
hi("EndOfBuffer", { fg = bg })
hi("Conceal", { fg = dark5 })
hi("MatchParen", { fg = orange, bold = true, underline = true })
hi("Visual", { bg = bg_highlight })
hi("VisualNOS", { bg = bg_highlight })
hi("Search", { fg = fg, bg = search_bg })
hi("IncSearch", { fg = bg, bg = orange })
hi("CurSearch", { fg = bg, bg = orange })
hi("Substitute", { fg = bg, bg = red })
hi("Pmenu", { fg = fg, bg = bg_float })
hi("PmenuSel", { fg = bg, bg = blue })
hi("PmenuSbar", { bg = fg_gutter })
hi("PmenuThumb", { bg = dark5 })
hi("WildMenu", { fg = bg, bg = blue })
hi("Question", { fg = green })
hi("QuickFixLine", { bg = bg_highlight })
hi("MoreMsg", { fg = blue })
hi("ModeMsg", { fg = fg_dark, bold = true })
hi("ErrorMsg", { fg = red })
hi("WarningMsg", { fg = yellow })
hi("Directory", { fg = blue })
hi("SpellBad", { sp = red, undercurl = true })
hi("SpellCap", { sp = yellow, undercurl = true })
hi("SpellLocal", { sp = green1, undercurl = true })
hi("SpellRare", { sp = cyan, undercurl = true })

hi("Comment", { fg = comment, italic = true })
hi("Constant", { fg = orange })
hi("String", { fg = green })
hi("Character", { fg = green })
hi("Number", { fg = orange })
hi("Boolean", { fg = orange })
hi("Float", { fg = orange })
hi("Identifier", { fg = magenta })
hi("Function", { fg = blue })
hi("Statement", { fg = magenta })
hi("Conditional", { fg = magenta })
hi("Repeat", { fg = magenta })
hi("Label", { fg = blue })
hi("Operator", { fg = blue5 })
hi("Keyword", { fg = cyan, italic = true })
hi("Exception", { fg = magenta })
hi("PreProc", { fg = cyan })
hi("Include", { fg = magenta })
hi("Define", { fg = magenta })
hi("Macro", { fg = magenta })
hi("PreCondit", { fg = cyan })
hi("Type", { fg = blue1 })
hi("StorageClass", { fg = magenta })
hi("Structure", { fg = magenta })
hi("Typedef", { fg = blue1 })
hi("Special", { fg = blue1 })
hi("SpecialChar", { fg = magenta })
hi("Tag", { fg = green1 })
hi("Delimiter", { fg = blue5 })
hi("SpecialComment", { fg = comment, bold = true })
hi("Debug", { fg = red })
hi("Underlined", { underline = true })
hi("Ignore", { fg = dark5 })
hi("Error", { fg = red })
hi("Todo", { fg = bg, bg = yellow, bold = true })

hi("@variable", { fg = fg })
hi("@variable.builtin", { fg = red })
hi("@variable.parameter", { fg = yellow })
hi("@variable.member", { fg = green1 })
hi("@constant", { fg = orange })
hi("@constant.builtin", { fg = orange })
hi("@constant.macro", { fg = orange })
hi("@module", { fg = magenta })
hi("@string", { fg = green })
hi("@string.escape", { fg = magenta })
hi("@string.regexp", { fg = blue6 })
hi("@string.special", { fg = blue5 })
hi("@character", { fg = green })
hi("@number", { fg = orange })
hi("@boolean", { fg = orange })
hi("@float", { fg = orange })
hi("@function", { fg = blue })
hi("@function.builtin", { fg = blue1 })
hi("@function.call", { fg = blue })
hi("@function.macro", { fg = magenta })
hi("@method", { fg = blue })
hi("@method.call", { fg = blue })
hi("@constructor", { fg = magenta })
hi("@keyword", { fg = cyan, italic = true })
hi("@keyword.function", { fg = magenta })
hi("@keyword.operator", { fg = magenta })
hi("@keyword.return", { fg = magenta })
hi("@keyword.import", { fg = cyan })
hi("@keyword.conditional", { fg = magenta })
hi("@keyword.repeat", { fg = magenta })
hi("@keyword.exception", { fg = magenta })
hi("@operator", { fg = blue5 })
hi("@punctuation.delimiter", { fg = blue5 })
hi("@punctuation.bracket", { fg = fg_dark })
hi("@punctuation.special", { fg = blue5 })
hi("@type", { fg = blue1 })
hi("@type.builtin", { fg = blue1 })
hi("@type.definition", { fg = blue1 })
hi("@type.qualifier", { fg = magenta })
hi("@property", { fg = green1 })
hi("@attribute", { fg = blue })
hi("@tag", { fg = red })
hi("@tag.attribute", { fg = yellow, italic = true })
hi("@tag.delimiter", { fg = blue5 })
hi("@markup.heading", { fg = blue, bold = true })
hi("@markup.strong", { bold = true })
hi("@markup.italic", { italic = true })
hi("@markup.strikethrough", { strikethrough = true })
hi("@markup.link", { fg = blue, underline = true })
hi("@markup.link.url", { fg = cyan, underline = true })
hi("@markup.raw", { fg = green })
hi("@markup.list", { fg = blue5 })
hi("@comment", { fg = comment, italic = true })

hi("@lsp.type.class", { fg = blue1 })
hi("@lsp.type.decorator", { fg = yellow })
hi("@lsp.type.enum", { fg = blue1 })
hi("@lsp.type.enumMember", { fg = cyan })
hi("@lsp.type.function", { fg = blue })
hi("@lsp.type.interface", { fg = blue1 })
hi("@lsp.type.macro", { fg = cyan })
hi("@lsp.type.method", { fg = blue })
hi("@lsp.type.namespace", { fg = blue1 })
hi("@lsp.type.parameter", { fg = yellow })
hi("@lsp.type.property", { fg = green1 })
hi("@lsp.type.struct", { fg = blue1 })
hi("@lsp.type.type", { fg = blue1 })
hi("@lsp.type.typeParameter", { fg = blue1 })
hi("@lsp.type.variable", { fg = fg })

hi("DiagnosticError", { fg = red })
hi("DiagnosticWarn", { fg = yellow })
hi("DiagnosticInfo", { fg = blue2 })
hi("DiagnosticHint", { fg = teal })
hi("DiagnosticOk", { fg = green })
hi("DiagnosticUnderlineError", { sp = red, undercurl = true })
hi("DiagnosticUnderlineWarn", { sp = yellow, undercurl = true })
hi("DiagnosticUnderlineInfo", { sp = blue2, undercurl = true })
hi("DiagnosticUnderlineHint", { sp = teal, undercurl = true })
hi("DiagnosticVirtualTextError", { fg = red, bg = diff_delete })
hi("DiagnosticVirtualTextWarn", { fg = yellow, bg = diff_change })
hi("DiagnosticVirtualTextInfo", { fg = blue2, bg = bg_highlight })
hi("DiagnosticVirtualTextHint", { fg = teal, bg = bg_highlight })

hi("GitSignsAdd", { fg = green })
hi("GitSignsChange", { fg = yellow })
hi("GitSignsDelete", { fg = red })
hi("GitSignsAddNr", { fg = green })
hi("GitSignsChangeNr", { fg = yellow })
hi("GitSignsDeleteNr", { fg = red })
hi("GitSignsAddLn", { bg = diff_add })
hi("GitSignsChangeLn", { bg = diff_change })
hi("GitSignsDeleteLn", { bg = diff_delete })

hi("DiffAdd", { bg = diff_add })
hi("DiffChange", { bg = diff_change })
hi("DiffDelete", { bg = diff_delete })
hi("DiffText", { bg = blue7 })
hi("diffAdded", { fg = green })
hi("diffRemoved", { fg = red })
hi("diffChanged", { fg = yellow })

hi("TelescopeNormal", { fg = fg, bg = bg_float })
hi("TelescopeBorder", { fg = blue, bg = bg_float })
hi("TelescopeTitle", { fg = blue, bold = true })
hi("TelescopePromptNormal", { fg = fg, bg = bg_highlight })
hi("TelescopePromptBorder", { fg = blue, bg = bg_highlight })
hi("TelescopePromptTitle", { fg = bg, bg = blue, bold = true })
hi("TelescopePromptPrefix", { fg = blue })
hi("TelescopeSelection", { bg = bg_highlight })
hi("TelescopeSelectionCaret", { fg = blue })
hi("TelescopeMatching", { fg = orange, bold = true })
hi("TelescopeResultsTitle", { fg = blue })
hi("TelescopePreviewTitle", { fg = blue })

hi("SnacksPickerInput", { fg = fg, bg = bg_highlight })
hi("SnacksPickerInputBorder", { fg = blue, bg = bg_highlight })
hi("SnacksPickerInputTitle", { fg = bg, bg = blue, bold = true })
hi("SnacksPickerList", { fg = fg, bg = bg_float })
hi("SnacksPickerListBorder", { fg = blue, bg = bg_float })
hi("SnacksPickerPreview", { fg = fg, bg = bg_float })
hi("SnacksPickerPreviewBorder", { fg = blue, bg = bg_float })
hi("SnacksPickerPreviewTitle", { fg = blue, bold = true })
hi("SnacksPickerListCursorLine", { bg = bg_highlight })
hi("SnacksPickerMatch", { fg = orange, bold = true })
hi("SnacksDashboardHeader", { fg = blue })
hi("SnacksDashboardIcon", { fg = magenta })
hi("SnacksDashboardKey", { fg = orange })
hi("SnacksDashboardDesc", { fg = fg_dark })
hi("SnacksDashboardFooter", { fg = comment })
hi("SnacksNotifierInfo", { fg = blue2 })
hi("SnacksNotifierWarn", { fg = yellow })
hi("SnacksNotifierError", { fg = red })
hi("SnacksIndent", { fg = fg_gutter })
hi("SnacksIndentScope", { fg = dark3 })

hi("NeoTreeNormal", { fg = fg, bg = bg_dark })
hi("NeoTreeNormalNC", { fg = fg, bg = bg_dark })
hi("NeoTreeDirectoryName", { fg = blue })
hi("NeoTreeDirectoryIcon", { fg = blue })
hi("NeoTreeRootName", { fg = magenta, bold = true })
hi("NeoTreeFileName", { fg = fg })
hi("NeoTreeFileIcon", { fg = fg })
hi("NeoTreeGitAdded", { fg = green })
hi("NeoTreeGitModified", { fg = yellow })
hi("NeoTreeGitDeleted", { fg = red })
hi("NeoTreeGitConflict", { fg = red, bold = true })
hi("NeoTreeGitUntracked", { fg = dark5 })
hi("NeoTreeIndentMarker", { fg = fg_gutter })
hi("NeoTreeWinSeparator", { fg = bg, bg = bg })
hi("NeoTreeCursorLine", { bg = bg_highlight })

hi("FlashLabel", { fg = bg, bg = magenta2, bold = true })
hi("FlashMatch", { fg = fg, bg = search_bg })
hi("FlashCurrent", { fg = bg, bg = orange })
hi("FlashBackdrop", { fg = comment })

hi("LazyButton", { fg = fg, bg = fg_gutter })
hi("LazyButtonActive", { fg = bg, bg = blue, bold = true })
hi("LazyH1", { fg = bg, bg = blue, bold = true })
hi("LazySpecial", { fg = blue })
hi("LazyProgressDone", { fg = blue })
hi("LazyProgressTodo", { fg = fg_gutter })

hi("MiniIndentscopeSymbol", { fg = dark3 })

hi("WhichKey", { fg = cyan })
hi("WhichKeyGroup", { fg = blue })
hi("WhichKeyDesc", { fg = fg_dark })
hi("WhichKeySeparator", { fg = comment })
hi("WhichKeyValue", { fg = dark5 })

hi("NoiceCmdlinePopup", { fg = fg, bg = bg_float })
hi("NoiceCmdlinePopupBorder", { fg = blue, bg = bg_float })
hi("NoiceCmdlineIcon", { fg = blue })
hi("NotifyINFOBorder", { fg = blue2 })
hi("NotifyINFOTitle", { fg = blue2 })
hi("NotifyINFOIcon", { fg = blue2 })
hi("NotifyWARNBorder", { fg = yellow })
hi("NotifyWARNTitle", { fg = yellow })
hi("NotifyWARNIcon", { fg = yellow })
hi("NotifyERRORBorder", { fg = red })
hi("NotifyERRORTitle", { fg = red })
hi("NotifyERRORIcon", { fg = red })
